version: "3.9"

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w!Q@W
      - MYSQL_DATABASE=blog
      - MYSQL_USER=kyoodong
      - MYSQL_PASSWORD=1q2w!Q@W
    container_name: tutorial-blog-mysql
    ports:
      - 3307:3306
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db